# Generated by Django 4.2.5 on 2023-09-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=255, null=True)),
                ('Fee', models.IntegerField(null=True)),
            ],
        ),
    ]
