# Generated by Django 4.2.5 on 2023-09-29 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('Joining_Date', models.DateField(null=True)),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseapp.course')),
            ],
        ),
    ]
