# Generated by Django 4.2.5 on 2023-09-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Joining_Date',
            new_name='joining_Date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='name',
        ),
    ]
