# Generated by Django 4.2.5 on 2023-09-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_rename_address_student_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='joining_Date',
            new_name='birth_date',
        ),
    ]
