# Generated by Django 4.2.5 on 2023-09-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_rename_joining_date_student_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birth_date',
            new_name='join_date',
        ),
    ]
